---
title: "Fisheries Network Analysis"
subtitle: "DSAN 6400: Network Analytics"
authors:
  - name: Morgan Dreiss
    email: med2106@georgetown.edu
    corresponding: true
  - name: Liz Kovalchuk
    email: ek976@georgetown.edu
    corresponding: true
title-block-banner: '#008080'
title-block-banner-color: 'black'
format:
  html:
    df-print: kable
    embed-resources: true
    link-external-newwindow: true
    link-external-icon: true
    link-citations: true
    code-fold: true
    toc: true
    toc-position: left  
    number-sections: true
    math: mathjax
  pdf:
    df-print: kable
    embed-resources: true
    link-external-newwindow: true
    link-external-icon: true
    link-citations: true
    code-fold: true
    toc: true
    toc-position: left  
    number-sections: true
    math: mathjax
bibliography: ../articles/fisheries_lib.bib
---


# Abstract

A "teaser" paragraphs summarizing the work (see below for more detail). 
  * The work isn't finished so this can just be an initial draft
  * An abstract is a 150 to 250-word paragraph that provides readers with a quick overview of your essay or report and its organization. It should express your thesis (or central idea) and your key points; it should also suggest any implications or applications of the research you discuss in the paper.
  * The function of an abstract is to describe, not to evaluate or defend, the paper.
  * The abstract should begin with a brief but precise statement of the problem or issue, followed by a description of the research method and design, the major findings, and the conclusions reached.
  * For more see: https://writingcenter.gmu.edu/guides/writing-an-abstract#:~:text=The%20function%20of%20an%20abstract,findings%2C%20and%20the%20conclusions%20reached.

## Keywords

Provide a list of keywords relevant to your work. 
  * Think of these as "search terms" that other researchers might google to find your paper. 

# Introduction

* Summary of the topic, why it is important, why the reader should continue, what work has been done in the past by other research groups, what are the “different points of views”/interpretations in the literature, what are you exploring, what questions are you trying to address, what are your goals and hypothesis, etc
  * Part of the introduction is a concise literature review. Therefore, along with the points mentioned above, make sure to summarize the nine publications (three per person) that you discussed in HW-1. 


## Background


## Literature Review

A 2018 paper @ford_chasing_2018 utilized Social Network Analysis (SNA) to identify key ships within the fishing industry in the Indian Ocean. The researchers utilized AIS data to infer relationships for vessel who operated in close proximity and found that Reefer (Refrigerated Cargo Vessels) and Bunkering (Fuel Resupply Ships) play a key role in the vessel network as identified by their eigenvector centrality.

Another paper @mulvaney_casting_2015 utilized survey data to establish connections between players in the Great Lake's local fisheries network. The paper discussed heavily their methodology constraints with the survey, but also concluded that the fisheries network included many informal and formal relationships, with the informal relationships forming a significant portion of the edges.

This paper @varlamis_building_2021 was interesting and was a deep dive on how they utilized AIS to create vessel traffic networks, but ultimately not helpful for this topic. 

@marin_network_2010 examined co-management networks in Chilean small-scale fisheries, finding that power was highly centralized in government institutions, with limited cooperation among fisher associations, and recommending policy changes for more participatory governance.

@dellapa_international_2013 used SNA to analyze trade flows of spiny dogfish, revealing how global trade relationships impact regional conservation outcomes and suggesting that trade regulations could promote sustainability.

@dellapa2014dogfish expanded on previous work to explore how stakeholder networks influence fishery management policies for spiny dogfish, showing the importance of network structures in shaping effective governance.

@nogueira2023dynamics analyzed fisheries in the Azores by converting time-series catch data into network structures, identifying key species associations and critical fishing nodes relevant for sustainable management strategies.

@nogueira_dynamics_2025 applied complex network metrics to fisheries data from the Azores Islands, uncovering structural patterns in the ecosystem and offering insights for sustainable policy and marine resource management.
